# action.yml
name: 'APIsec Scan'
description: 'Continuous, automated, comprehensive API Security Testing'
inputs:
  apisec-username:
    description: 'The APIsec username with which the scans will be executed'
    required: true
    default: ''
  apisec-password:
    description: 'The Password of the APIsec user with which the scans will be executed'
    required: true
    default: '' 
  apisec-project:
    description: 'The Name of the project for security scan'
    required: true
    default: ''
  apisec-profile:  
    description: 'The Name of the scan profile to be executed'
    required: false
    default: 'Master'
  apisec-region:  
    description: 'The location the scan will be executed in'
    required: false
    default: ''
 
runs:
  using: "composite"
  steps:
    - run:  ${GITHUB_ACTION_PATH}/apisec-run-scan.sh ${{inputs.apisec-username}} ${{ inputs.apisec-password }} ${{ inputs.apisec-project }} ${{ inputs.apisec-profile }} ${{ inputs.apisec-region }} 
      shell: bash
